# Generated by Django 3.1.2 on 2020-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Contact_us',
                'verbose_name_plural': 'Contact_uss',
            },
        ),
    ]
