# Generated by Django 3.1.2 on 2020-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to='product_image')),
                ('developer', models.CharField(max_length=300)),
                ('technology_used', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=300)),
            ],
        ),
    ]
