# Generated by Django 3.1.2 on 2020-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='blog_image')),
                ('clap', models.IntegerField()),
                ('auther', models.CharField(max_length=100)),
                ('blog_refrences', models.TextField(max_length=1000)),
            ],
        ),
    ]
